### ISSUE TITLE
how to generate the bbox region file

### ISSUE THREAD

**Issue by kracwarlock** [LuoweiZhou/detectron-vlp#3]
i was able to generate the 2000 hdf5 files in the `feat_cls_1000` folder for `coco` and also 1000 files under the `raw_bbox` folder. how do i generate `coco_detection_vg_thresh0.2_feat_gvd_checkpoint_trainvaltest.h5`?

**Comment by LuoweiZhou** [comment]
@kracwarlock Merge all the files under `raw_bbox` into a single `.h5` file.
