### ISSUE TITLE
Visualization for comparison

### ISSUE THREAD

**Issue by nikky4D** [LuoweiZhou/detectron-vlp#6]
Hi,
I would like to test my implementation to make sure it matches up with yours. Would you have a test video or videos you recommend I use to compare my results to yours? Just to make sure it is running properly. 

Also, if I wanted to visualize the features, is there a code I can use for that?

Thank you for all your help.

**Comment by LuoweiZhou** [comment]
@nikky4D We have a code to visualize the [BBox](https://github.com/facebookresearch/grounded-video-description/blob/master/main.py#L72) in GVD, but not for features.

I'd suggest you simply print out the `sum` or `norm` of the feature file and compare it against our provided file. You can also do it at a finer level, say indexing a block from the tensor to see if the values match our file, like I mentioned here: https://github.com/facebookresearch/grounded-video-description/issues/20#issuecomment-610036948 If you see error around or < 1e-5, this is normal due to precision errors.

**Comment by nikky4D** [comment]
Thank you. I'll get to work on it over the next two weeks. Thank you for all your help.

**Comment by MarcusNerva** [comment]
@nikky4D Hi amigo! Which enviroment did you choose for [detectron-vlp](https://github.com/LuoweiZhou/detectron-vlp) ? [GVD](https://github.com/facebookresearch/grounded-video-description/blob/master/cfgs/conda_env_gvd_py3.yml) or [VLP](https://github.com/LuoweiZhou/VLP/blob/master/misc/vlp.yml)? Or just prepare conda environment by yourself? Would you please share your requirements.txt?

**Comment by nikky4D** [comment]
@MarcusNerva I was working in colab, and using the install process for detectron-vlp. My environment was based on GVD but had to be modified to get it working in colab.

**Comment by MarcusNerva** [comment]
@nikky4D Could you tell me the version of choosed pytorch? I meet this problem:

> [I net_async_base.h:205] Using specified CPU pool size: 4; device id: -1
[I net_async_base.h:210] Created new CPU pool, size: 4; device id: -1
[E net_async_base.cc:377] [enforce fail at math_gpu.cu:569] status == CUBLAS_STATUS_SUCCESS. 13 vs 0. Error at: /opt/conda/conda-bld/pytorch_1556653000816/work/caffe2/utils/math_gpu.cu:569: CUBLAS_STATUS_EXECUTION_FAILED
Error from operator: 
input: "gpu_0/fc7" input: "gpu_0/bbox_pred_w" input: "gpu_0/bbox_pred_b" output: "gpu_0/bbox_pred" name: "" type: "FC" arg { name: "use_cudnn" i: 1 } arg { name: "cudnn_exhaustive_search" i: 0 } arg { name: "order" s: "NCHW" } device_option { device_type: 1 device_id: 0 }frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x59 (0x7f65a9797409 in /home/marcusnerva/anaconda3/envs/gvd_pt1_1/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #1: void caffe2::math::Gemm<float, caffe2::CUDAContext, caffe2::DefaultEngine>(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, float const*, float, float*, caffe2::CUDAContext*, caffe2::TensorProto_DataType) + 0x6da (0x7f65ac6f399a in /home/marcusnerva/anaconda3/envs/gvd_pt1_1/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2_gpu.so)
frame #2: <unknown function> + 0x14e3730 (0x7f65ab326730 in /home/marcusnerva/anaconda3/envs/gvd_pt1_1/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2_gpu.so)
frame #3: <unknown function> + 0x14d8e88 (0x7f65ab31be88 in /home/marcusnerva/anaconda3/envs/gvd_pt1_1/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2_gpu.so)
frame #4: <unknown function> + 0x13cb0b5 (0x7f65ab20e0b5 in /home/marcusnerva/anaconda3/envs/gvd_pt1_1/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2_gpu.so)
frame #5: caffe2::AsyncNetBase::run(int, int) + 0x144 (0x7f65cdd1cb94 in /home/marcusnerva/anaconda3/envs/gvd_pt1_1/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #6: <unknown function> + 0x168f009 (0x7f65cdd23009 in /home/marcusnerva/anaconda3/envs/gvd_pt1_1/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #7: c10::ThreadPool::main_loop(unsigned long) + 0x2a3 (0x7f65a97912f3 in /home/marcusnerva/anaconda3/envs/gvd_pt1_1/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #8: <unknown function> + 0xb8678 (0x7f65e4a5b678 in /home/marcusnerva/anaconda3/envs/gvd_pt1_1/bin/../lib/libstdc++.so.6)
frame #9: <unknown function> + 0x9609 (0x7f65eb05d609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #10: clone + 0x43 (0x7f65eae2a293 in /lib/x86_64-linux-gnu/libc.so.6)
,  op FC

So confusing.
