### ISSUE TITLE
anet_detection_vg_fc6_feat_100rois.h5 problem

### ISSUE THREAD

**Issue by pandababyer** [LuoweiZhou/detectron-vlp#7]
Hi, Luowei. Thank you for sharing the feature extraction code !  But I have this problem since your last change. It seems like a error when write the .h5 file 
https://github.com/LuoweiZhou/detectron-vlp/blob/9ecc981d196d989b25dadd32b3680c8be93e9b06/tools/extract_features_gvd_anet.py#L271
![image](https://user-images.githubusercontent.com/24407543/99226087-22a36780-2824-11eb-8ad8-39a83cf34be3.png)

Looking forward to your reply. Thanks.

**Comment by LuoweiZhou** [comment]
@pandababyer It should actually be `reshape` instead of `view`. Sorry for the inconvenience. Will update.

**Comment by pandababyer** [comment]
Thank you for the reply
